deployment:
  tasks:
    - export DEPLOYPATH=/home/yongcapc/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R project $DEPLOYPATH
    - /bin/cp -R qrcode $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
